// SPDX-FileCopyrightText: 2026 fprintd (pure-Rust) contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

//! # fprint-integration
//!
//! The one crate that names every backend. `ARCHITECTURE.md`'s rule is that dependency arrows
//! point only toward the leaves: `fprint-core` cannot name a backend, and a backend cannot name
//! its siblings. Serving one device from the native Rust backend and another from the libfprint
//! shim under a single [`Backend`](fprint_core::Backend) therefore happens above the core, in one
//! place. This crate depends on the backends, never the reverse.
//!
//! [`CompositeBackend`] holds the concrete backends; its associated device is the enum
//! [`CompositeDevice`], one variant per backend. Enumeration concatenates the backends' devices;
//! its `open` tries native first and falls through to the shim.
//!
//! ## The coexistence seam
//!
//! This seam lets one daemon serve pure-Rust native readers alongside libfprint-shim readers,
//! presenting both as a single [`Backend`](fprint_core::Backend). The shipped `fprintd` binary
//! does **not** wire it in: the only native reader is a virtual test device, which is not offered
//! to real users (`ARCHITECTURE.md`). The daemon drives the shim directly and this crate stays out
//! of its graph. The seam carries no `unsafe` and its delegation is covered by the crate's own
//! tests.
//!
//! ## Why hand-written `match`, not `enum_dispatch`
//!
//! `CompositeDevice`'s [`Device`](fprint_core::Device) impl is delegated by hand — an explicit
//! `match self { Native(d) => d.method(..).await, Shim(d) => d.method(..).await }` per method
//! — rather than generated by `enum_dispatch`:
//!
//! 1. **Native AFIT is `dyn`-incompatible.** `fprint-core`'s trait uses native `async fn` in
//!    trait (static dispatch, no `async-trait`, `!Send`-friendly — see `ARCHITECTURE.md`).
//!    `enum_dispatch` bridges an enum *to* a `dyn`-object-safe trait; an `async fn`-in-trait
//!    method has an anonymous, per-impl return future and is not object-safe, so the macro
//!    has nothing to bridge to. A `match` needs no object safety: each arm calls a concrete
//!    method and `.await`s a concrete future.
//!
//! 2. **One arm is `cfg`-gated.** The `Shim` variant exists only on
//!    `cfg(target_os = "linux")`. Hand-written arms carry that `#[cfg(...)]` attribute
//!    directly, so the enum has two variants on Linux and one everywhere else, and this
//!    crate compiles and tests native-only on a Windows dev box. A derive that enumerates
//!    variants would have to be taught the same `cfg`.
//!
//! 3. **No proc-macro dependency.** The seam is a dozen two-line methods; a `match` states
//!    where each call goes without one.

#![forbid(unsafe_code)]

mod composite;

pub use composite::{CompositeBackend, CompositeDevice};
