// SPDX-FileCopyrightText: 2026 libfprint-rs (pure-Rust) contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

//! # fp-integration
//!
//! The one crate that knows *every* backend. Everything below it — `fp-core`, each
//! `fp-backend-*` leaf — obeys `ARCHITECTURE.md`'s single rule: dependency arrows point only
//! toward the leaves, and no crate ever references its implementors. `fp-core` cannot name a
//! backend; a backend cannot name its siblings. Yet during migration we genuinely want *one
//! device served by native Rust and another by the libfprint shim, under a single
//! [`Backend`](fp_core::Backend)*. That heterogeneity has to live *somewhere*, above the
//! core, in exactly one place. This is that place.
//!
//! [`CompositeBackend`] holds the concrete backends; its associated device is the enum
//! [`CompositeDevice`], one variant per backend. Enumeration concatenates the backends'
//! devices; [`CompositeBackend::open`] tries native first and falls through to the shim.
//! The dependency arrows still point down — this crate depends on the backends, never the
//! reverse — so the crystal stays a crystal.
//!
//! ## Why hand-written `match`, not `enum_dispatch`
//!
//! `CompositeDevice`'s [`Device`](fp_core::Device) impl is delegated by hand — an explicit
//! `match self { Native(d) => d.method(..).await, Shim(d) => d.method(..).await }` per method
//! — rather than generated by `enum_dispatch`. Three forces make the hand-written seam the
//! beautiful one here:
//!
//! 1. **Native AFIT is `dyn`-incompatible.** `fp-core`'s trait uses native `async fn` in
//!    trait (static dispatch, no `async-trait`, `!Send`-friendly — see `ARCHITECTURE.md`).
//!    `enum_dispatch` bridges an enum *to* a `dyn`-object-safe trait; an `async fn`-in-trait
//!    method has an anonymous, per-impl return future and is not object-safe, so the macro
//!    has nothing to bridge to. A `match` needs no object safety: each arm calls a concrete
//!    method and `.await`s a concrete future.
//!
//! 2. **One arm is `cfg`-gated.** The `Shim` variant exists only on
//!    `cfg(target_os = "linux")`. Hand-written arms carry that `#[cfg(...)]` attribute
//!    naturally, so the enum has two variants on Linux and one everywhere else — and this
//!    crate compiles and tests native-only on a Windows dev box. A derive that enumerates
//!    variants would have to be taught the same `cfg`, re-deriving what a `match` already
//!    says plainly.
//!
//! 3. **Zero-dep honesty.** The seam is a dozen two-line methods. Pulling in a proc-macro
//!    crate to write code this small and this readable would trade clarity for a dependency —
//!    the opposite of the trade this project makes everywhere else. The delegation *is* the
//!    documentation: you can read exactly where each call goes.
//!
//! The reverse asymmetry from the core applies here too: a hand-written `match` can always
//! grow a variant or a `dyn` bridge later; it commits us to nothing.

// Pure delegation — the seam stays as clean as the crystal it composes.
#![forbid(unsafe_code)]

mod composite;

pub use composite::{CompositeBackend, CompositeDevice};
