// SPDX-FileCopyrightText: 2026 fprintd (pure-Rust) contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

//! A classification of known USB fingerprint sensors, generated from the libfprint driver
//! id-tables — do not edit by hand; regenerate with `cargo xtask device-db`.
//!
//! Each row is an interoperability fact: a `(vid, pid)` a libfprint driver claims, the
//! driver that claims it, and whether that driver produces a host-side image (so the
//! [`crate::FrameSource`] seam can reach it) or matches on the chip. `fpdev probe` reads
//! it to tell a user whether their sensor is reachable before they start on a driver.
//!
//! Rows are sorted by `(vid, pid)` and each pair appears once.

/// How a sensor's driver does matching, which decides whether a host-image seam can reach it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Family {
    /// Streams pixels to the host; all matching runs here, so [`crate::FrameSource`] can drive it.
    HostImage,
    /// Enrolls and matches on the sensor; no image reaches the host.
    MatchOnChip,
    /// Neither archetype fits with confidence; not pinned to a seam.
    Other,
}

/// One known device: the USB ids it presents, the libfprint driver that claims it, and how
/// that driver matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DeviceRecord {
    pub vid: u16,
    pub pid: u16,
    /// The libfprint driver id that claims this device.
    pub driver: &'static str,
    pub family: Family,
}

/// Every classified device, sorted by `(vid, pid)`; 256 rows, no duplicate keys.
pub static DEVICES: &[DeviceRecord] = &[
    DeviceRecord {
        vid: 0x045e,
        pid: 0x00bb,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x045e,
        pid: 0x00bc,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x045e,
        pid: 0x00bd,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x045e,
        pid: 0x00ca,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x0483,
        pid: 0x2015,
        driver: "upektc",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x0483,
        pid: 0x2016,
        driver: "upekts",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x0483,
        pid: 0x2017,
        driver: "upektc",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0903,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0907,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c01,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c02,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c03,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c04,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c05,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c06,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c07,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c08,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c09,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0a,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0b,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0c,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0d,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0e,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c0f,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c10,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c11,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c12,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c13,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c14,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c15,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c16,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c17,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c18,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c19,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1a,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1b,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1c,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1d,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1e,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c1f,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c20,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c21,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c22,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c23,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c24,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c25,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c26,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c27,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c28,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c29,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2a,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2b,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2c,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2d,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2e,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c2f,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c30,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c31,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c32,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c33,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c3d,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c42,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c4b,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c4d,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c4f,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c58,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c63,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c6e,
        driver: "elan",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c7d,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c7e,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c82,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c88,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c8c,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c8d,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c98,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c99,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c9c,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c9d,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0c9f,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0ca3,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0ca7,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0ca8,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0cb0,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x04f3,
        pid: 0x0cb2,
        driver: "elanmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x05ba,
        pid: 0x0007,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x05ba,
        pid: 0x0008,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x05ba,
        pid: 0x000a,
        driver: "uru4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x061a,
        pid: 0x0110,
        driver: "vcom5s",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00bd,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00c2,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00c4,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00c6,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00df,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00e9,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00f0,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00f9,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x00fc,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0100,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0103,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0104,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0106,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0107,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0108,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0109,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x010a,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0123,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0124,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0126,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0129,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x015f,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0168,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0169,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x016c,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0173,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x0174,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x019d,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x019f,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x01a0,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x06cb,
        pid: 0x01a4,
        driver: "synaptics",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1600,
        driver: "aes1610",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1660,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1680,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1681,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1682,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1683,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1684,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1685,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1686,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1687,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1688,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x1689,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168a,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168b,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168c,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168d,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168e,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x168f,
        driver: "aes1660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2500,
        driver: "aes2501",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2550,
        driver: "aes2550",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2580,
        driver: "aes2501",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2660,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2680,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2681,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2682,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2683,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2684,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2685,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2686,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2687,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2688,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2689,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268a,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268b,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268c,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268d,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268e,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x268f,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2691,
        driver: "aes2660",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x2810,
        driver: "aes2550",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x5501,
        driver: "aes4000",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x08ff,
        pid: 0x5731,
        driver: "aes3500",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x0bda,
        pid: 0x5813,
        driver: "realtek",
        family: Family::Other,
    },
    DeviceRecord {
        vid: 0x0bda,
        pid: 0x5816,
        driver: "realtek",
        family: Family::Other,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0x9524,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0x9544,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0x9b24,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xa305,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xa306,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xc844,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xd205,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xd805,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xda04,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x10a5,
        pid: 0xffe0,
        driver: "fpcmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1162,
        pid: 0x2200,
        driver: "secugen",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0001,
        driver: "vfs101",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0005,
        driver: "vfs301",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0008,
        driver: "vfs301",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0010,
        driver: "vfs5011",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0011,
        driver: "vfs5011",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0015,
        driver: "vfs5011",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0017,
        driver: "vfs5011",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0018,
        driver: "vfs5011",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0050,
        driver: "vfs0050",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x138a,
        pid: 0x0091,
        driver: "vfs7552",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x147e,
        pid: 0x1000,
        driver: "upeksonly",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x147e,
        pid: 0x1001,
        driver: "upeksonly",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x147e,
        pid: 0x2016,
        driver: "upeksonly",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x147e,
        pid: 0x2020,
        driver: "upektc_img",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x147e,
        pid: 0x3001,
        driver: "upektc",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0570,
        driver: "egis0570",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0571,
        driver: "egis0570",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0582,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0583,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0584,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0586,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0587,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0588,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x05a1,
        driver: "egismoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x05ae,
        driver: "egis_etu905",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x0603,
        driver: "etes603",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x1c7a,
        pid: 0x9201,
        driver: "egis_etu905",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2541,
        pid: 0xfa03,
        driver: "realtek",
        family: Family::Other,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x5840,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6014,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6090,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6092,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6094,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x609a,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x609c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x60a2,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x60a4,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x60bc,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x60c2,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6304,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x631c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x633c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x634c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6382,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6384,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x639c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x63ac,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x63bc,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x63cc,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6496,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x650a,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x650c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6512,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6582,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6584,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x658c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6592,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6594,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x659a,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x659c,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x66a9,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6890,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x689a,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6984,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x27c6,
        pid: 0x6a94,
        driver: "goodixmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x077a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x079a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x1579,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x5158,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x6553,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0x9e48,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa27a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa57a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa78a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa959,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa97a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xa99a,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x2808,
        pid: 0xd979,
        driver: "focaltech_moc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x298d,
        pid: 0x1010,
        driver: "nb1010",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x298d,
        pid: 0x2020,
        driver: "nb1010",
        family: Family::HostImage,
    },
    DeviceRecord {
        vid: 0x3274,
        pid: 0x8012,
        driver: "mafpmoc",
        family: Family::MatchOnChip,
    },
    DeviceRecord {
        vid: 0x3274,
        pid: 0x9003,
        driver: "realtek",
        family: Family::Other,
    },
];

/// The record for a `(vid, pid)`, if one is known.
///
/// A binary search over [`DEVICES`], which is sorted by key.
#[must_use]
pub fn lookup(vid: u16, pid: u16) -> Option<&'static DeviceRecord> {
    DEVICES
        .binary_search_by(|r| (r.vid, r.pid).cmp(&(vid, pid)))
        .ok()
        .map(|i| &DEVICES[i])
}

/// The whole table.
#[must_use]
pub fn all() -> &'static [DeviceRecord] {
    DEVICES
}
